### ISSUE TITLE
Trouble building for UE 4.20

### ISSUE THREAD

**Issue by profbetis** [getnamo/opencl-ue4#3]
It looks like dev for this stopped like a year ago, but I think this looks pretty interesting to play with! I'm using Unreal Engine 4.20 and its automatic rebuild of the project failed. I'm not well-versed with editing anything that would be necessary for doing that. Is it possible to make and push the necessary changes or provide the details for me to try myself and make a pull request?

**Comment by getnamo** [comment]
This is just an experimental curiosity plugin, not exactly in a production usable state atm. It's still missing byte array data pointer passing (https://github.com/getnamo/opencl-ue4/issues/2) for it to work well with generic opencl kernels with arbitrary input types. If you're C++ versed however, it correctly includes the OpenCL header and you should be able to modify the main function https://github.com/getnamo/opencl-ue4/blob/master/Source/OpenCL/Private/OpenCLPlugin.cpp#L131 to suit your needs.

That said, I just checked and the plugin still recompiled without issue for 4.20, so made a the same basic release available here: https://github.com/getnamo/opencl-ue4/releases/tag/0.3.1

Keep in mind that OpenCL by definition is a fairly low level language and some domain knowledge is expected. The original thought here was that you could probably define the input types in blueprint and have the opencl kernels hot-reloaded as you edit them, so you could largely avoid the strict C++ data binding and have a very easy dev time with opencl kernels. Then with https://github.com/getnamo/opencl-ue4/issues/1 you could in theory have a no-data transfer to textures/vertices and mix them with ue4 texture further downstream to do some cool things. Never got that far, but it's open source, contributions welcome :)

**Comment by getnamo** [comment]
Forgot to mention: to recompile a plugin for a current engine build, all you do is make a C++ UE4 project and include the plugin. Rebuild the project in Visual Studio and the plugin will get rebuilt along with it. In this case no code changes were necessary.

**Comment by profbetis** [comment]
Awesome, thanks for the info :)
